# This is a basic workflow to help you get started with Actions

name: Running Benchmarks JMH

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8", "11", "13", "14"]
    name: Java ${{ matrix.java }} sample
    steps:
      - name: setup-maven-settings
        uses: s4u/maven-settings-action@v1
        with:
         servers: '[{"id": "github", "username": "x-access-token", "password": "${GITHUB_TOKEN}"}]'

      - uses: actions/checkout@v2
      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          mvn clean deploy
          java -jar target/benchmarks.jar IntegerListFilter -rf json > IntegerListFilter.${{ matrix.java }}.json 
          java -jar target/benchmarks.jar IntegerListSum -rf json > IntegerListSum.${{ matrix.java }}.json 
          
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: test results
          path: |
            IntegerListSum.${{ matrix.java }}.json
            IntegerListFilter.${{ matrix.java }}.json
